controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.8
      stopped_velocity_tolerance: 0.02
      joint1: {trajectory: 0.2, goal: 0.1}
      joint2: {trajectory: 0.2, goal: 0.1}
      joint3: {trajectory: 0.2, goal: 0.1}
      joint4: {trajectory: 0.2, goal: 0.1}
      joint5: {trajectory: 0.2, goal: 0.1}
      joint6: {trajectory: 0.2, goal: 0.1}
