gz_ros_control:
  ros__parameters:
    position_proportional_gain: 0.5

controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - grip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      arm_joint1: {trajectory: 1.0, goal: 0.2}
      arm_joint2: {trajectory: 1.0, goal: 0.2}
      arm_joint3: {trajectory: 1.0, goal: 0.2}
      arm_joint4: {trajectory: 1.0, goal: 0.2}
      arm_joint5: {trajectory: 1.0, goal: 0.2}
      grip_joint: {trajectory: 1.0, goal: 0.2}
